### ISSUE TITLE
Net::HTTP is not required and cause an uninitialized constant exception

### ISSUE THREAD

**Issue by lukad** [anakinj/jwk-loader#1]
Fetching a JWKS from a URI always fails unless `'net/http'` is required.
Check out this small snippet to reproduce the bug.

``` ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'jwt'
  gem 'jwk-loader'
end

token = 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImZvbyJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.PNIggnDN5MkPhnJO_hG7pjc1DMzCHv85HAxo9UPr65XQevxjVXzGNie-11qkHbP8Pqz3nkHD5oDLK0BF6hLJy4-mXiMfoOzV8eGiY1IYbhJka6llhiBECJDScQZnQLEZar-kJKgfQ6UGj-q5yS2aCG4ThTDnb2QAA4rDbB61JEo-OJ8C2VvEbN4Wmtp6mz_g1qSUVMyQL3GTDPLa2JYQTMer36e4YoDPr3GtNjBzfXaXDtfhIZAToV1OgNPw0f0TDBvGlgL-GmTN1oack8cEbDBamcM0bj-lFOYVQiNaAg7Y8eY3Sy4feADMtRwdBM4Mw561cfBIEHd24UUH71UMkA'

JWT.decode(token, nil, true, algorithm: 'RS512', jwks: JwkLoader.for_uri(uri: 'http://example.com/jwks'))
```

```
/Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwk-loader-0.1.0/lib/jwk_loader/jwks.rb:12:in `from_uri': uninitialized constant #<Class:JwkLoader::Jwks>::Net (NameError)

        response = Net::HTTP.get_response(uri)
                   ^^^
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwk-loader-0.1.0/lib/jwk_loader/jwks_uri_provider.rb:43:in `from_uri'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwk-loader-0.1.0/lib/jwk_loader/jwks_uri_provider.rb:25:in `jwks'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwk-loader-0.1.0/lib/jwk_loader/jwks_uri_provider.rb:19:in `call'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:46:in `load_keys'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:41:in `jwks'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:50:in `jwks_keys'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:54:in `find_key'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:26:in `resolve_key'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/jwk/key_finder.rb:15:in `key_for'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/decode.rb:60:in `set_key'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt/decode.rb:29:in `decode_segments'
	from /Users/luka/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/jwt-2.5.0/lib/jwt.rb:29:in `decode'
	from ./bug.rb:14:in `<main>'
```

The test are probably only passing because vcr/webmock/etc. requires `'net/http'`

**Comment by anakinj** [comment]
Wow. Just learned about this `bundler/inline` thanks :)

**Comment by lukad** [comment]
You're welcome! Thanks for the gem btw. Looks like you created it just in time when I needed it :)

**Comment by anakinj** [comment]
Great to hear. Having implemented this load+cache+invalidate process already in a few different services and the talks about security and caching pitfalls in https://github.com/jwt/ruby-jwt it kinda feels like a thing that deserves it's own little library.
